//
// Copyright (C) Capital One Labs.
//

package com.capitalone.cardcompanion.common;

/**
 * Inbound call type.
 * Calls into Orchestrator.
 */
public enum InboundCallType {
    ISSO_AUTHENTICATE,
    ISSO_VERIFY_MFA_ANSWERS,
    ISSO_VERIFY_PASSWORD,

    CREATE_SURESWIPE_DEVICE_ENROLLMENT,
    DELETE_SURESWIPE_DEVICE_ENROLLMENT,
    UPDATE_SURESWIPE_DEVICE_ENROLLMENT,
    SURESWIPE_AUTHENTICATE,
    SURESWIPE_VERIFY,

    CREATE_TOUCH_ID_DEVICE_ENROLLMENT,
    DELETE_TOUCH_ID_DEVICE_ENROLLMENT,
    TOUCH_ID_AUTHENTICATE,
    DELETE_TOUCH_ID,

    DIRECT_BANK_AUTHENTICATE_ID,
    DIRECT_BANK_VERIFY_MFA_ANSWERS,
    DIRECT_BANK_VERIFY_PIN,

    GET_GIFT_CARD_CATALOG,
    GET_GIFT_CARD_PRODUCT,

    GET_USER_GIFT_CARDS,
    GET_GIFT_CARD,
    PURCHASE_GIFT_CARD,
    DELETE_GIFT_CARD,
    RELOAD_GIFT_CARD,

    CREATE_PASSBOOK_PASS,

    GET_USER_PAYMENT_CARDS,
    GET_PAYMENT_CARD_OTP,

    GET_REWARDS_BALANCE,

    GET_TRANSACTIONS,

    ERASE_PURCHASE,
    STATEMENT_CREDIT,

    GET_ALERT_SUBSCRIPTIONS,
    UPDATE_ALERT_SUBSCRIPTION,
    UPDATE_CONTACT_POINT,

    PASSBOOK_GET_LATEST_VERSION_OF_PASS,
    PASSBOOK_GET_SERIAL_NUMBERS_FOR_DEVICE,
    PASSBOOK_REGISTER_DEVICE,
    PASSBOOK_DEREGISTER_DEVICE,

    DINERO_REGISTER_DEVICE_FOR_DPAN,
    DINERO_DEREGISTER_DEVICE_FOR_DPAN,
    DINERO_DEREGISTER_DEVICE,
    DINERO_REREGISTER_DEVICE,
    DINERO_GET_TRANSACTIONS,
    DINERO_GET_MESSAGES
}
