//
// Copyright (C) Capital One Labs.
//

package com.capitalone.cardcompanion.common;

/**
 * Outbound call type.
 * Calls from Orchestrator.
 */
public enum OutboundCallType {
    ISSO_AUTHENTICATE,
    ISSO_GET_MFA_STATUS,
    ISSO_GET_MFA_QUESTIONS,
    ISSO_VERIFY_MFA_ANSWERS,

    GET_SURESWIPE_DEVICE_ENROLLMENT,
    CREATE_SURESWIPE_DEVICE_ENROLLMENT,
    DELETE_SURESWIPE_DEVICE_ENROLLMENT,
    UPDATE_SURESWIPE_DEVICE_ENROLLMENT,
    SURESWIPE_AUTHENTICATE,

    DIRECT_BANK_AUTHENTICATE_ID,
    DIRECT_BANK_VERIFY_MFA_ANSWERS,
    DIRECT_BANK_VERIFY_PIN,
    GET_DIRECT_BANK_ALTERNATE_CUSTOMER_ID,

    GET_ACCOUNTS_CUSTOMER_PROFILE,

    GET_DIRECT_BANK_ACCOUNT_SUMMARIES,

    GET_CREDIT_CARD_ACCOUNT_SUMMARY,

    GET_CREDIT_CARD_TRANSACTIONS,

    GET_DEPOSIT_ACCOUNT_SUMMARY,

    GET_DEPOSIT_ACCOUNT_TRANSACTIONS,

    GET_PAYMENT_CARD_ENCRYPTED_DATA_BY_CUSTOMER_REFERENCE_ID,
    GET_PAYMENT_CARD_ENCRYPTED_DATA_BY_SSO_ID,
    GET_PAYMENT_CARDS_BY_CUSTOMER_REFERENCE_ID_ENCRYPTED_DATA,
    GET_PAYMENT_CARDS_BY_SSO_ID_ENCRYPTED_DATA,
    GET_PAYMENT_CARDS_BY_CUSTOMER_REFERENCE_ID_NO_ENCRYPTED_DATA,
    GET_PAYMENT_CARDS_BY_SSO_ID_NO_ENCRYPTED_DATA,

    GET_PAYMENT_CARDS_BY_ACCOUNT_REFERENCE_ID,
    GET_PAYMENT_CARD_BY_ACCOUNT_REFERENCE_ID_AND_LAST_FOUR,

    GET_REWARDS_BALANCE,
    REDEEM_REWARDS,
    CANCEL_REWARDS_REDEMPTION,

    GET_REFERENCE_ID_BY_ACCOUNT_THREE_PART_KEY,

    GET_GIFT_CARD_CATALOG,
    GET_GIFT_CARD_PRODUCT,
    GET_GIFT_CARD_OWNER,
    CREATE_GIFT_CARD_OWNER,
    GET_GIFT_CARD,
    CREATE_GIFT_CARD,
    CREATE_EGIFT,
    RELOAD_GIFT_CARD,
    HIDE_GIFT_CARD,

    ADD_TRANSACTION_METADATA_TAGS,
    DELETE_TRANSACTION_METADATA_TAG,
    GET_TRANSACTION_METADATA_TAGS_FOR_ACCOUNT,
    GET_TRANSACTION_METADATA_TAGS_FOR_TRANSACTION,
    GET_DISTINCT_TRANSACTION_METADATA_TAGS_FOR_ACCOUNT,
    GET_CARD_REFERENCE_ID,
    GET_PROFILE_REFERENCE_ID,
    POST_CARD_PROVISION,
    PUT_CARD_PROVISION_CONFIRM,
    POST_CARD_PROVISION_REPLENISH,
    PUT_CARD_PROVISION_REPLENISH_CONFIRM,
    POST_CARD_PROVISION_CHECK_STATUS,
    POST_CARD_PROVISION_REGISTER_DEVICE,
    PUT_CARD_PROVISION_DELETE,

}
